"use client";
import { BookOpen, TrendingUp, BarChart3, Brain, Megaphone } from "lucide-react";
import type { Category } from "@/components/courses/course";

export const coursesData: Category[] = [
    {
        id: 'software-testing',
        name: 'Software Testing',
        description: 'Master quality assurance and testing methodologies for robust software delivery',
        icon: <BookOpen className="w-6 h-6" />,
        color: 'text-blue-600',
        borderColor: 'border-blue-200',
        bgColor: 'bg-blue-50',
        iconBgColor: 'bg-blue-100',
        courses: [
            {
                id: 'st-1',
                title: 'Manual Software Testing',
                href: 'manual-testing-course',
                category: 'Software Testing',
                description: 'Learn to facilitate Scrum teams and drive Agile projects effectively.',
                duration: '50 Hours',
                students: '1200+',
                rating: 4.9,
                level: 'Beginner',
                popular: true,
                link: '/manual-testing-course',
                icon: 'BookOpen',
                features: ['ISTQB Foundation Prep', 'Test Case Design', 'Defect Life Cycle'],
                skills: ['Manual Testing', 'SDLC', 'Test Cases'],
                syllabusLink: 'https://www.cinutedigital.com/downloads/manual-software-testing.pdf',
                price: "$299" // estimated
            },
            {
                id: 'st-2',
                title: 'Advanced Automation Testing',
                href: 'automation-testing-course',
                category: 'Software Testing',
                description: 'Drive product vision and delivery in SAFe settings.',
                duration: '85 Hours',
                students: '950+',
                rating: 4.8,
                level: 'Intermediate',
                popular: true,
                link: '/automation-testing-course',
                icon: 'Code',
                features: ['Selenium WebDriver', 'CI/CD Integration (Jenkins)', 'Advanced Java Concepts'],
                skills: ['Automation', 'Selenium', 'Java', 'Jenkins'],
                syllabusLink: 'https://www.cinutedigital.com/downloads/advanced-automation-testing.pdf',
                price: "$429"
            },
            {
                id: 'st-3',
                title: 'API Testing using POSTMAN and RestAPIs',
                href: 'api-testing',
                category: 'Software Testing',
                description: 'Master API testing using Postman, Rest Assured, and Groovy for robust web services.',
                duration: '15 Hours',
                students: '700+',
                rating: 4.7,
                level: 'Intermediate',
                popular: false,
                link: '/api-testing',
                icon: 'Zap',
                features: ['Postman & Swagger', 'Rest Assured Framework', 'JSON/XML Validation'],
                skills: ['API Testing', 'Postman', 'Rest Assured'],
                syllabusLink: 'https://www.cinutedigital.com/downloads/api-testing-using-postman-and-restapis.pdf',
                price: "$249"
            },
            {
                id: 'st-4',
                title: 'ETL Testing Course',
                href: 'etl-testing',
                category: 'Software Testing',
                description: 'Master the art of leading enterprise-wide Agile transformations using the Scaled Agile Framework (SAFe).',
                duration: '100 Hours',
                students: '500+',
                rating: 4.6,
                level: 'Intermediate',
                popular: true,
                link: '/etl-testing',
                icon: 'Shield',
                features: ['Data Warehousing Concepts', 'SQL Testing', 'ETL Tools', 'ETL Testing Lifecycle & Test Planning'],
                skills: ['ETL', 'SQL', 'Data Warehousing'],
                syllabusLink: 'https://www.cinutedigital.com/downloads/etl-testing-&-development.pdf',
                price: "$329"
            },
            {
                id: 'st-5',
                title: 'Database Management System using MySQL',
                href: 'dbms-course',
                category: 'Software Testing',
                description: 'Master SQL queries, database design, and management with MySQL. Learn to build scalable and efficient database solutions.',
                duration: '40 Hours',
                students: '500+',
                rating: 4.8,
                level: 'Beginner',
                popular: false,
                link: '/dbms-course',
                icon: 'Database',
                features: ['SQL Fundamentals', 'Database Design', 'Normalization', 'Complex Queries'],
                skills: ['MySQL', 'Database Design', 'SQL'],
                syllabusLink: 'https://www.cinutedigital.com/downloads/database-management-system-using-mysql.pdf',
                price: "$259"
            },
            {
                id: 'st-6',
                title: 'Advanced Software Testing',
                href: 'advance-software-testing',
                category: 'Software Testing',
                description: 'Go beyond the basics—build strategies, manage risk, and measure quality with actionable metrics.',
                duration: '95 Hours',
                students: '2,268+',
                rating: 4.8,
                level: 'Beginner',
                popular: true,
                link: '/advance-software-testing',
                icon: 'ChartBar',
                features: ['Test Strategy & Risk-Based Testing', 'Traceability & Coverage Techniques', 'Test Management & Metrics', 'Performance/Security Test Readiness'],
                skills: ['Test Strategy', 'Test Management', 'Quality Metrics'],
                syllabusLink: 'https://www.cinutedigital.com/downloads/advanced-software-testing.pdf',
                price: "$349"
            },
            {
                id: 'st-7',
                title: 'Master Program in Java Programming',
                href: 'java-course',
                category: 'Software Testing',
                description: 'Become industry-ready with Core Java, OOP, Collections, JDBC, Spring Boot, REST APIs, unit testing, and deployment. Build portfolio projects and earn a QR-verified certificate.',
                duration: '30 Hours',
                students: 'Not specified',
                rating: 4.9,
                level: 'Beginner',
                popular: true,
                link: '/java-course',
                icon: 'Cog',
                features: [
                    'Core Java Fundamentals (Variables, OOP, Collections, Exception Handling)',
                    'Enterprise Java (Spring Boot, REST APIs, Hibernate/JPA)',
                    'Testing & Build Tools (JUnit/Mockito, Maven/Gradle)',
                    'CI/CD & Deployment (GitHub Actions, Docker, AWS Basics)'
                ],
                skills: ['Java', 'Spring Boot', 'Hibernate', 'Microservices'],
                syllabusLink: 'https://www.cinutedigital.com/downloads/java-programming.pdf',
                price: "$399"
            },
            {
                id: 'st-8',
                title: 'Advanced Manual & Automation Testing — Master Program',
                href: 'advance-manual-automation-testing',
                category: 'Software Testing',
                description: 'End-to-end mastery: advanced test strategy and leadership combined with enterprise-grade automation and CI/CD.',
                duration: '180 Hours',
                students: '2,302+',
                rating: 4.8,
                level: 'Beginner',
                popular: true,
                link: '/advance-manual-automation-testing',
                icon: 'Trophy',
                features: [
                    'Risk-Based Strategy & Quality Metrics',
                    'Advanced Test Design & Bug Advocacy',
                    'Automation Frameworks (POM/Hybrid, API + UI)',
                    'CI/CD, Parallel & Cross-Browser at Scale'
                ],
                skills: ['Manual Testing', 'Automation Testing', 'CI/CD', 'Framework Design'],
                syllabusLink: 'https://www.cinutedigital.com/downloads/advanced-manual-and-automation-testing-master-program.pdf',
                price: "$899"
            },
            {
                id: 'st-9',
                title: 'Python Programming',
                category: 'Software Testing',
                href: 'python-course',
                description: 'Master Python Programming from absolute basics w/ advanced concepts! Dive deep into Python syntax, OOP, automation scripting, and real-world problem-solving.',
                duration: '30 Hours',
                students: '2,268+',
                rating: 4.8,
                level: 'Beginner',
                popular: true,
                link: '/python-course',
                icon: 'TrendingUp',
                features: ['Python Basics Guide', 'Advanced Python Coding', 'Learn Python Fast', 'Real-World Python Projects & Automation Mastery'],
                skills: ['Python', 'Scripting', 'Automation'],
                syllabusLink: 'https://www.cinutedigital.com/downloads/python-programming.pdf',
                price: "$299"
            },
        ]
    },
    {
        id: 'data-science',
        name: 'Data Science',
        description: 'Unlock insights from data with advanced analytics, machine learning, and statistical modeling',
        icon: <TrendingUp className="w-6 h-6" />,
        color: 'text-purple-600',
        borderColor: 'border-purple-200',
        bgColor: 'bg-purple-50',
        iconBgColor: 'bg-purple-100',
        courses: [
            {
                id: 'ds-1',
                title: 'Machine Learning and Data Science with Python - Hero Program',
                href: 'machine-learning-course',
                category: 'Data Science',
                description: 'Master Machine Learning & Data Science with Python in our Hero Program! Hands-on projects, expert mentorship & job-ready skills.',
                duration: '95 Hours',
                students: '2,200+',
                rating: 4.8,
                level: 'Beginner',
                popular: true,
                link: '/machine-learning-course',
                icon: 'TrendingUp',
                features: ['Machine Learning Python', 'Data Science Hero', 'Python ML Program', 'MLOps & Production-Ready ML Systems'],
                skills: ['Python', 'Machine Learning', 'Data Science', 'MLOps'],
                syllabusLink: 'https://www.cinutedigital.com/downloads/machine-learning-and-data-science-with-python-hero-program.pdf',
                price: "$499"
            },
            {
                id: 'ds-2',
                title: 'Deep Learning, NLP and Generative AI',
                href: 'generative-ai-course',
                category: 'Data Science',
                description: 'Dive into Deep Learning, NLP & Generative AI! Master neural networks, text processing & AI creation with hands-on projects.',
                duration: '55 Hours',
                students: '2,217+',
                rating: 4.8,
                level: 'Beginner',
                popular: true,
                link: '/generative-ai-course',
                icon: 'TrendingUp',
                features: ['Deep Learning Basics', 'NLP Mastery Course', 'Clustering', 'Generative AI Skills'],
                skills: ['Deep Learning', 'NLP', 'Generative AI'],
                syllabusLink: 'https://www.cinutedigital.com/downloads/deep-learning-nlp-and-generativeai.pdf',
                price: "$599"
            },
            {
                id: 'ds-3',
                title: 'Advanced Data Science and Machine Learning Masterclass',
                href: 'data-science-course',
                category: 'Data Science',
                description: 'Elevate your career with Advanced Data Science & Machine Learning Masterclass! Deep-dive into algorithms, big data & AI.',
                duration: '200 Hours',
                students: '2,234+',
                rating: 4.8,
                level: 'Beginner',
                popular: false,
                link: '/data-science-course',
                icon: 'TrendingUp',
                features: ['Advanced Data Science', 'Machine Learning Masterclass', 'AI Algorithms Pro', 'Generative AI & LLM Engineering in Practice'],
                skills: ['Advanced ML', 'Algorithms', 'AI'],
                syllabusLink: 'https://www.cinutedigital.com/downloads/advanced-data-science-and-machine-learning-masterclass.pdf',
                price: "$699"
            },
            {
                id: 'ds-4',
                title: 'Comprehensive Data Science and AI - Master Program',
                href: 'ai-course',
                category: 'Data Science',
                description: 'Unlock expertise in Comprehensive Data Science & AI Master Program! From ML to deep learning, big data & ethics.',
                duration: '255 Hours',
                students: '2,251+',
                rating: 4.8,
                level: 'Beginner',
                popular: true,
                link: '/ai-course',
                icon: 'TrendingUp',
                features: ['Data Science Mastery', 'AI Master Program', 'Comprehensive ML AI'],
                skills: ['Data Science', 'AI', 'Big Data', 'Ethics'],
                syllabusLink: 'https://www.cinutedigital.com/downloads/comprehensive-data-science-and-ai-master-program.pdf',
                price: "$1199"
            },
            {
                id: 'ds-5',
                title: 'Machine Learning Algorithms using python Programming',
                href: 'machine-learning-using-python',
                category: 'Data Science',
                description: 'Master Machine Learning Algorithms using Python Programming! Implement regression, classification, clustering & more with scikit-learn.',
                duration: '45 Hours',
                students: '2,285+',
                rating: 4.8,
                level: 'Beginner',
                popular: true,
                link: '/machine-learning-using-python',
                icon: 'TrendingUp',
                features: ['ML Algorithms Python', 'Python ML Coding', 'Scikit-Learn Mastery'],
                skills: ['Machine Learning', 'Python', 'Scikit-Learn'],
                syllabusLink: 'https://www.cinutedigital.com/downloads/machine-learning-algorithms-using-python-programming.pdf',
                price: "$449"
            },
            {
                id: 'ds-6',
                title: 'Machine Learning and Data Visualization using R Programming',
                href: 'data-visualization-in-r-programming',
                category: 'Data Science',
                description: 'Master Machine Learning & Data Visualization using R Programming! Explore ggplot2, tidyverse, ML models & interactive dashboards.',
                duration: '20 Hours',
                students: '2,302+',
                rating: 4.8,
                level: 'Beginner',
                popular: true,
                link: '/data-visualization-in-r-programming',
                icon: 'TrendingUp',
                features: ['R ML Visualization', 'Data Viz R', 'R Programming ML'],
                skills: ['R Programming', 'Data Visualization', 'Machine Learning'],
                syllabusLink: 'https://www.cinutedigital.com/downloads/machine-learning-and-data-visualization-using-r-programming.pdf',
                price: "$299"
            },
            {
                id: 'ds-7',
                title: 'Python Programming',
                category: 'Data Science',
                href: 'python-course',
                description: 'Master Python Programming from absolute basics w/ advanced concepts! Dive deep into Python syntax, OOP, automation scripting, and real-world problem-solving.',
                duration: '30 Hours',
                students: '2,268+',
                rating: 4.8,
                level: 'Beginner',
                popular: true,
                link: '/python-course',
                icon: 'TrendingUp',
                features: ['Python Basics Guide', 'Advanced Python Coding', 'Learn Python Fast', 'Real-World Python Projects & Automation Mastery'],
                skills: ['Python', 'Scripting', 'Automation'],
                syllabusLink: 'https://www.cinutedigital.com/downloads/python-programming.pdf',
                price: "$299"
            },
        ]
    },
    {
        id: 'business-intelligence',
        name: 'Business Intelligence',
        description: 'Transform data into actionable insights with powerful BI tools and analytics platforms',
        icon: <BarChart3 className="w-6 h-6" />,
        color: 'text-cyan-600',
        borderColor: 'border-cyan-200',
        bgColor: 'bg-cyan-50',
        iconBgColor: 'bg-cyan-100',
        courses: [
            {
                id: 'bi-1',
                title: 'Advanced Data Analytics - Hero Program',
                href: 'data-analytics',
                category: 'Business Intelligence',
                description: 'Elevate to pro with Advanced Data Analytics Hero Program! Master SQL, Python, Tableau, predictive modeling & big data.',
                duration: '110 Hours',
                students: '2,200+',
                rating: 4.8,
                level: 'Beginner',
                popular: true,
                link: '/data-analytics',
                icon: 'BarChart3',
                features: ['Advanced Analytics Hero', 'Data Analytics Mastery', 'Predictive Analytics Pro'],
                skills: ['Data Analytics', 'SQL', 'Python', 'Tableau'],
                syllabusLink: 'https://www.cinutedigital.com/downloads/advanced-data-analytics-hero-program.pdf',
                price: "$449"
            },
            {
                id: 'bi-2',
                title: 'Advanced Data Analytics with Python Libraries',
                href: 'data-analytics-python',
                category: 'Business Intelligence',
                description: 'Master Advanced Data Analytics with Python Libraries! Harness Pandas, NumPy, Matplotlib, Seaborn & Scikit-learn for insights & predictions.',
                duration: '20 Hours',
                students: '2,217+',
                rating: 4.8,
                level: 'Beginner',
                popular: true,
                link: '/data-analytics-python',
                icon: 'BarChart3',
                features: ['Python Data Analytics', 'Advanced Analytics Libraries', 'Pandas NumPy Mastery'],
                skills: ['Python', 'Data Analytics', 'Pandas', 'NumPy'],
                syllabusLink: 'https://www.cinutedigital.com/downloads/advanced-data-analytics-with-python-libraries.pdf',
                price: "$299"
            },
            {
                id: 'bi-3',
                title: 'Advanced Excel for Data Analytics & Visualization',
                href: 'data-analytics-and-visualization',
                category: 'Business Intelligence',
                description: 'Master Excel for Data Analytics & Visualization! Unlock PivotTables, Power Query, charts, dashboards & advanced formulas.',
                duration: '20 Hours',
                students: '2,234+',
                rating: 4.8,
                level: 'Beginner',
                popular: true,
                link: '/data-analytics-and-visualization',
                icon: 'BarChart3',
                features: ['Excel Data Analytics', 'Data Visualization Excel', 'Excel Analytics Mastery'],
                skills: ['Excel', 'Data Analytics', 'Data Visualization'],
                syllabusLink: 'https://www.cinutedigital.com/downloads/advanced-excel-for-data-analytics-&-visualization.pdf',
                price: "$199"
            },
            {
                id: 'bi-4',
                title: 'Data Analytics & Visualization with Tableau',
                href: 'data-analytics-with-tableau',
                category: 'Business Intelligence',
                description: 'Master Data Analytics & Visualization with Tableau! Build interactive dashboards, explore data with drag-and-drop, uncover insights & tell stories.',
                duration: '20 Hours',
                students: '2,251+',
                rating: 4.8,
                level: 'Beginner',
                popular: true,
                link: '/data-analytics-with-tableau',
                icon: 'BarChart3',
                features: ['Tableau Data Analytics', 'Visualization Mastery Tableau', 'Interactive Dashboards Tableau'],
                skills: ['Tableau', 'Data Analytics', 'Data Visualization'],
                syllabusLink: 'https://www.cinutedigital.com/downloads/data-analytics-&-visualization-with-tableau.pdf',
                price: "$299"
            },
            {
                id: 'bi-5',
                title: 'Data Analytics & Visualization with Power BI',
                href: 'power-bi-course',
                category: 'Business Intelligence',
                description: 'Master Data Analytics & Visualization with Power BI! Create stunning dashboards, DAX formulas, data modeling & insights.',
                duration: '20 Hours',
                students: '2,268+',
                rating: 4.8,
                level: 'Beginner',
                popular: true,
                link: '/power-bi-course',
                icon: 'BarChart3',
                features: ['Power BI Analytics', 'Data Visualization Power BI', 'Power BI Mastery'],
                skills: ['Power BI', 'Data Analytics', 'Data Visualization'],
                syllabusLink: 'https://www.cinutedigital.com/downloads/data-analytics-&-visualization-with-power-bi.pdf',
                price: "$299"
            },
            {
                id: 'bi-6',
                title: 'Data Analytics With BI And Big Data Engineering Master Program',
                href: 'masters-in-data-engineering',
                category: 'Business Intelligence',
                description: 'Master Data Analytics with BI & Big Data Engineering Master Program! Harness Power BI, Tableau, Spark, Hadoop & ETL pipelines.',
                duration: '155 Hours',
                students: '2,285+',
                rating: 4.8,
                level: 'Beginner',
                popular: true,
                link: '/masters-in-data-engineering',
                icon: 'BarChart3',
                features: ['Power BI/Tableau', 'Big Data Concepts', 'Data Warehousing'],
                skills: ['Data Analytics', 'Big Data', 'Data Engineering', 'BI'],
                syllabusLink: 'https://www.cinutedigital.com/downloads/data-analytics-with-bi-and-big-data-engineering-master-program.pdf',
                price: "$899"
            },
        ],
    },
    {
        id: 'artificial-intelligence',
        name: 'Artificial Intelligence',
        description: 'Explore the future of technology with AI, deep learning, and intelligent automation systems',
        icon: <Brain className="w-6 h-6" />,
        color: 'text-pink-600',
        borderColor: 'border-pink-200',
        bgColor: 'bg-pink-50',
        iconBgColor: 'bg-pink-100',
        courses: [
            {
                id: 'ai-1',
                title: 'Prompt Engineering with Gen AI',
                href: 'prompt-engineering-course',
                category: 'Artificial Intelligence',
                description: 'Become an AI Expert in Mumbai. Master the fundamentals of AI, deep learning, NLP, and intelligent automation systems.',
                duration: '20 Hours',
                students: '10,000+',
                rating: 4.9,
                level: 'Master',
                popular: true,
                link: '/prompt-engineering-course',
                icon: 'Brain',
                features: ['AI Foundations & Generative AI', 'Large Language Models & Multimodal AI', 'Prompt Engineering Techniques', 'Responsible AI, Governance & Capstone'],
                skills: ['Artificial Intelligence', 'Prompt Engineering', 'GenAI'],
                syllabusLink: 'https://www.cinutedigital.com/downloads/prompt-engineering-with-gen-ai.pdf',
                price: "$299"
            },
        ],
    },
    {
        id: "digital-marketing",
        name: "Digital Marketing",
        description:
            "Master SEO, SEM, social media, content, and analytics to drive measurable growth across channels.",
        icon: <Megaphone className="w-6 h-6" />,
        color: "text-blue-600",
        borderColor: "border-blue-200",
        bgColor: "bg-blue-50",
        iconBgColor: "bg-blue-100",
        courses: [
            {
                id: 'dm-1',
                title: 'AI-Driven Digital Marketing & Analytics',
                href: 'digital-marketing-course',
                category: 'Digital Marketing',
                description: 'End-to-end mastery: full-funnel strategies, analytics-driven decisions, and campaign leadership.',
                duration: '80 Hours',
                students: '2,200+',
                rating: 4.8,
                level: 'Master',
                popular: true,
                link: '/digital-marketing-course',
                icon: 'Smartphone',
                features: ['Holistic Strategy & Planning', 'Advanced Analytics & Attribution', 'Multi-Channel Campaigns', 'Portfolio & Freelance Readiness'],
                skills: ['Digital Marketing', 'AI', 'Analytics'],
                syllabusLink: 'https://www.cinutedigital.com/downloads/ai-driven-digital-marketing-&-analytics.pdf',
                price: "$599"
            },
            {
                id: 'dm-2',
                title: 'Digital Marketing and AI (For Business Owners)',
                href: 'ai-in-digital-marketing',
                category: 'Digital Marketing',
                description: 'Leverage AI to grow your business faster and cheaper – no agency needed. Perfect for founders, CEOs & solopreneurs.',
                duration: '50 Hours',
                students: '2,217+',
                rating: 4.8,
                level: 'Beginner',
                popular: true,
                link: '/ai-in-digital-marketing',
                icon: 'Smartphone',
                features: ['AI-Powered Market Research & Customer Avatars', 'Automated Content Creation at Scale', 'AI Ads Optimization & Predictive Analytics', 'Build Your Own No-Code AI Marketing Team'],
                skills: ['Digital Marketing', 'AI', 'Business Strategy'],
                syllabusLink: 'https://www.cinutedigital.com/downloads/digital-marketing-and-ai-for-business-owners-digital-marketing-and-ai-for-business-owners.pdf',
                price: "$399"
            },
            {
                id: 'dm-3',
                title: 'Digital Marketing With AI Bootcamp',
                href: 'ai-bootcamp',
                category: 'Digital Marketing',
                description: 'Become a future-ready digital marketer: master AI tools, prompt engineering for ads & content, and run hyper-personalized campaigns.',
                duration: '30 Hours',
                students: '2,234+',
                rating: 4.8,
                level: 'Beginner',
                popular: true,
                link: '/ai-bootcamp',
                icon: 'Smartphone',
                features: ['Prompt Engineering for Ads & Copywriting', 'AI Tools Mastery (ChatGPT, Claude, Midjourney, ElevenLabs, etc.)', 'Automated Funnels & Omnichannel AI Workflows', 'AI-Driven Performance Marketing & ROAS Optimization'],
                skills: ['Digital Marketing', 'AI', 'Bootcamp'],
                syllabusLink: 'https://www.cinutedigital.com/downloads/digital-marketing-with-ai-bootcamp-digital-marketing-with-ai-bootcamp.pdf',
                price: "$299"
            },
            {
                id: "dm-4",
                title: "Digital Marketing and Analytics - Master Program",
                href: "digital-marketing-course",
                description:
                    "End-to-end training in SEO, Google & Meta Ads, social media strategy, GA4, and Looker Studio—learn to plan, execute, and measure ROI with real projects.",
                duration: "20 weeks",
                level: "Beginner–Advanced",
                students: "2,900+",
                rating: 4.9,
                price: "$599",
                skills: [
                    "SEO",
                    "Google Ads (SEM)",
                    "Meta Ads",
                    "GA4",
                    "Looker Studio",
                    "Content Strategy",
                    "A/B Testing"
                ],
                icon: <BarChart3 className="w-5 h-5" />,
            },
        ],
    },
    // {
    //     id: 'web-development',
    //     name: 'Web Development',
    //     ... (Existing Web Development placeholder if needed, skipping to match new data)
    // }
];